### ISSUE TITLE
License Update

### ISSUE THREAD

**Issue by tylerezimmerman** [DelineaXPM/ansible-core-collection#26]
Looks like this is GPL 3.0. This this intentional? IF not, can it be changed to MIT?

**Comment by sheldonhull** [comment]
[Required License Type for Ansible](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_in_groups.html)

> All other files shipped with Ansible, including all modules, must be licensed under the GPL license (GPLv3 or later).
