### ISSUE TITLE
Question: Can we use this with an on-premise installation of Thycotic Privilege Vault?

### ISSUE THREAD

**Issue by timothydilbert** [DelineaXPM/ansible-core-collection#37]
I have Ansible playbooks where I need secrets stored in an on-premise Privilege Vault. Does this module support pulling secrets from our on-premise Vault?

**Comment by sheldonhull** [comment]
@timothydilbert the current plugin in this collection is specifically for using Delinea DevOps Secret Vault. I think you'll want to explore the other integration options for Secret Server. cc @tylerezimmerman in case you are aware of any integrations to point Timothy too. Cheers.
