### ISSUE TITLE
DSV plugin example documentation isn't showing up in Ansible Galaxy or easily found without going into code

### ISSUE THREAD

**Issue by ai-ryanbess** [DelineaXPM/ansible-core-collection#45]
Can you please share an example of how to use this?

**Comment by ai-ryanbess** [comment]
@sheldonhull thanks for the quick response.  The documentation helps a little.  Please look here and see how cisco has documented their modules https://docs.ansible.com/ansible/latest/collections/cisco/ise/endpoint_module.html.  Perhaps you could make a youtube video showing how to use your plugin?

**Comment by sheldonhull** [comment]
@ai-ryanbess found this link

https://docs.ansible.com/ansible/latest/collections/community/general/dsv_lookup.html

We need to pin that on our readme. 
Is that better? 

If this isn't enough do you have any specific areas that would be useful to expand on?

**Comment by sheldonhull** [comment]
Please reopen if this reference doesn't help. I'll make sure to update the README to include this rendered documentation link.

**Comment by ai-ryanbess** [comment]
I think what's throwing me off is the use of the environment variable.  Let me do some research on that.

**Comment by ai-ryanbess** [comment]
are you able to provide an example of a complete playbook that would log into secret server and pull out a secret.  Something similar to what was opened here https://github.com/ansible-collections/community.general/issues/3057

- hosts: localhost
  connection: local
  vars:
    thycotic_host: example.secretservercloud.com
    thycotic_username: "{{ tss_user }}"
    thycotic_password: "{{ tss_password }}"
    thycotic_base_uri: https://{{ thycotic_host }}
    secret_id: 1655
    secret: "{{ lookup('community.general.tss',
                                               registration_authority_secret_id,
                                               base_url=thycotic_base_uri,
                                               username=thycotic_username,
                                               password=thycotic_password)
                               }}"
     secret_dict: "{{ registration_authority_secret['items']
                                        | items2dict(key_name='slug', value_name='itemValue')
                                    }}"
    secret_value: "{{ secret_dict['password'] }}" 
  tasks:
  - name: display secret value
    ansible.builtin.debug:
      var: secret_value

**Comment by andrii-zakurenyi** [comment]
@ai-ryanbess here are some examples with no environment variables used. 

- Example with all available arguments provided:

```yaml
- hosts: localhost
  vars:
      secret1: >-
        {{ lookup(
            'delinea.core.dsv',
            'PASTE_SECRET_PATH_HERE',
            tenant='PASTE_TENANT_NAME_HERE',
            tld='com',
            url_template='https://{}.secretsvaultcloud.{}/v1',
            client_id='PASTE_YOUR_CLIENT_ID_HERE',
            client_secret='PASTE_CLIENT_SECRET_HERE',
        ) }}
  tasks:
    - debug: msg='Full secret retrieved from DSV = {{ secret1 }}'
    - debug: msg='Only secret data = {{ secret1["data"] }}'
```

- Example with optional arguments skipped:

```yaml
- hosts: localhost
  vars:
      secret1: >-
        {{ lookup(
            'delinea.core.dsv',
            'PASTE_SECRET_PATH_HERE',
            tenant='PASTE_TENANT_NAME_HERE',
            client_id='PASTE_CLIENT_ID_HERE',
            client_secret='PASTE_CLIENT_SECRET_HERE',
        ) }}
  tasks:
    - debug: msg='Full secret retrieved from DSV = {{ secret1 }}'
    - debug: msg='Only secret data = {{ secret1["data"] }}'
```

- Example with second variable used to store secret data:

```yaml
- hosts: localhost
  vars:
      secret1: >-
        {{ lookup(
            'delinea.core.dsv',
            'PASTE_SECRET_PATH_HERE',
            tenant='PASTE_TENANT_NAME_HERE',
            client_id='PASTE_CLIENT_ID_HERE',
            client_secret='PASTE_CLIENT_SECRET_HERE',
        ) }}
      secret1_data: '{{ secret1["data"] }}'
  tasks:
    - debug: msg='Only secret data = {{ secret1_data }}'
```

**Comment by ai-ryanbess** [comment]
Does this apply for on prem Secret Server? We're running 11.1.7.  So lets say our FQDN is secretserver.domain.com what would we feed in.  I don't understand what "paint_secret_path_here" or "Paste_Tenant_name_here" means.  Can you please clarify?

**Comment by ai-ryanbess** [comment]
Made some progress.  When i log into the GUI the secrets i'm trying to get are in https://secretserver.domain.com/app/#/folders/526


---
- hosts: localhost
  connection: local
  vars:
      secret1: >-
        "{{ lookup(
              'delinea.core.dsv', '/app/#/folders/526',
              tld='domain.com',
              url_template='https://{}.{}',
              tenant='secretserver',
              client_id='someuser',
              client_secret='somepassword'
        ) }}"
  tasks:
    - name: Print Data
      debug:
        var: secret1


getting this now
fatal: [localhost]: FAILED! => {
    "msg": "An unhandled exception occurred while templating '\"{{ lookup(\n      'delinea.core.dsv', '/app/#/folders/526',\n      tld='domain.com',\n      url_template='https://{}.{}',\n      tenant='secretserver',\n      client_id='someuser',\n      client_secret='somepassword'\n) }}\"'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'delinea.core.dsv'. Error was a <class 'ansible.errors.AnsibleError'>, original message: DevOps Secrets Vault lookup failure: <Response [200]>. DevOps Secrets Vault lookup failure: <Response [200]>"

**Comment by sheldonhull** [comment]
@ai-ryanbess are you trying to look up a secret server value? 
This is for Delinea DevOps Secrets vault, not Secret Server.
You'd have to use this with DSV specifically.

**Comment by ai-ryanbess** [comment]
Thanks for your help and time i'm going to close this out....got it working with the general.tss
